enum SpecialWinCondition {
  ACQUIRE_ARTIFACT = 0x00,
  ACCUMULATE_CREATURES = 0x01,
  ACCUMULATE_RESOURCES = 0x02,
  UPGRADE_TOWN = 0x03,
  BUILD_GRAIL = 0x04,
  DEFEAT_HERO = 0x05,
  CAPTURE_TOWN = 0x06,
  DEFEAT_MONSTER = 0x07,
  FLAG_DWELLINGS = 0x08,
  FLAG_MINES = 0x09,
  TRANSPORT_ARTIFACT = 0x0A
}

export default SpecialWinCondition
